--- # Notification and Handling events
- hosts: centos1
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: yes
  connection: ssh
  tasks:
  - name: install nginx webserver
    yum:
      name: nginx
      state: latest
    notify:
    - enable and start the nginx service
  handlers: 
  - name: enable and start the nginx service
    service:
      name: nginx
      enabled: yes
      state: restarted


