--- # Testing the J2 template module
- hosts: apacheweb:debian
  user: ansible
  connection: ssh
  sudo: yes
  gather_facts: yes
  vars:
   userName: ansible
   userPassword: password123
   connectionType: SFTP
  tasks:
    - name: Install the configuration file customized for the system
      template: src=test.conf.j2 dest=/home/ansible/test.conf owner=ansible group=ansible mode=750
