--- # Web Playbook
- hosts: apacheweb
  user: ansible
  sudo : yes
  connection: ssh
  gather_facts: yes
  vars_files:
    - variables/variable.yml
  tasks:
    - include: packages/packages.yml
    - include: commands/commands.yml
  handlers:  
    - include: handlers/handlers.yml


