- name: Install the NFS Server and Utilities
  yum: pkg={{ item }} state=latest
  with_items:
  - "{{ nfsutils_pkg }}"
  - "{{ nfslibs_pkg }}"
- name: Copy the export file to remote server
  copy: src=exports.template dest=/etc/exports owner=root group=root mode=644
  notify:
  - StartServerServices
