--- # Apache2 Module Example
- hosts: appserver
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks: 
    - name: Disable the alias module in Apache2
      apache2_module: state=absent name=alias

