--- # Kernel_blacklist module demo
- hosts: apacheweb
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
   - name: Blacklist the Dummy Kernel Module
     kernel_blacklist: name=dummy state=present
