--- # Copy Module Example
- hosts: apacheweb
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks: 
  - name: Copy from the files directory test file
    action: copy src=files/shak259.txt dest=/home/ansible/shak259.txt owner=ansible group=ansible mode=0655 backup=yes

