--- # Example of Filesystem Module
- hosts: apacheweb
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Format the remote data partition
      filesystem: fstype=ext3 dev=/dev/xvdf1 opts="-cc"
