--- # Example of Git Module
- hosts: apacheweb
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
     - name: Checking out a git repo on the remote server
       git: repo=ssh://ansible@shakeelj6/home/ansible/shak253 dest=/home/ansible/gitrepo

