--- # Example of Group Module
- hosts: apacheweb
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Add a new group called newgroup
      group: name=newgroup253 state=absent gid=4200 system=yes
