--- #HTpasswd Example
- hosts: appserver
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
   - name: Install the Python dependencies
     apt: pkg=python-passlib state=latest
   - name: Adding a user to Website Authentication
     htpasswd: path=/etc/apache2/.htpasswd name=zayaan state=absent
