--- # Example of Mail Module
- hosts: apacheweb
  user: ansible
  connection: ssh
  tasks:
    - name: Send an email to test user indicating build completion
      mail:
        host='localhost'
        port=25
        to="ansible"
        subject="Our Host if finished Deploying"
        body='System called {{ ansible_hostname }} has been successfully setup'
    
