--- # Example of Mount Module
- hosts: apacheweb
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: mount the remote data partition
      mount: name=/mnt/data src=/dev/xvdf1 fstype=ext3 opts=rw state=present
