--- # Prompt for user package Example
- hosts: apacheweb
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  vars: 
    playbook_version: 0.01b
  vars_prompt: 
     - name: pkgtoinstall
       prompt: Install Which Package?
       default: telnet
       private: no
  tasks:
     - name: Install the indicated package
       yum: pkg={{ pkgtoinstall }} state=absent
       
       
