--- # Example Stat Module
- hosts: apacheweb
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: Does a file/directory in a path exist or not?
    stat: path=/home/ansible/abc
      register: result
  - debug: msg="The Path Exists and is a Directory"
      when: p.stat.isdir is defined and p.stat.isdir
