--- # Example of Unarchive Module
- hosts: apacheweb
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: copy and unarchive a file
      unarchive: src=/home/ansible/local/shakeel.tar.gz dest=/home/ansible/local copy=no
