--- # Master Playbook for Webservers
- hosts: apacheweb
  user: ansible
  sudo: yes
  connection: ssh
  pre_tasks:
    - name: When did the role start
      raw: date > /home/ansible/startofrole.log
  roles:
    - redhat_webservers
  post_tasks:
    - name: When did the role stop
      raw: date > /home/ansible/stopofrole.log
