- name: Install (RedHat/ Centos)apache Web Server
  yum: pkg={{ redhat_apache }} state=latest
  when: "ansible_os_family == 'RedHat'"
  notify: Restart HTTPD
  ignore_errors: yes
- name: Install (Debian/Ubuntu) Apache Web Server
  apt: pkg={{ debian_apache }} state=latest
  when: "ansible_os_family == 'Debian'"
  notify: Restart Apache2
  ignore_errors: yes
- debug:
  when: "ansible_os_family == 'RedHat'"
  notify: InstallTelnet
  ignore_errors: yes
  changed_when: true
