--- # Master Playbook for Webservers
- hosts: apacheweb
  user: ansible
  sudo: yes
  connection: ssh
  pre_tasks:
  - name: When did the role start
    raw: date > /home/ansible/startofrole253.log
  roles:
  - redhat.apachewebserver
  post_tasks:
  - name: When did the role end
    raw: date > /home/ansible/stopofrole253.log
